title: Patch Cao · Home
description: Sharing knowledge&thoughts born of my life
url: http://PatchCao.github.io
avatar: /assets/img/avatar.jpg
favicon: /assets/img/favicon.ico

about:
  - paragraph: A Man who travels the world writing codes.
    text_align: center
    links:
      - name: Patch Cao · Home
        url: http://PatchCao.github.io
        external: true
    
